trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps: 
- task: katalonTask@0
  inputs:
    version: '8.3.5'
    executeArgs: '-browserType="Chrome (headless)" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Regression Suite/TS Cure Health Care" -apiKey="6067c065-a8eb-44c1-b724-e1851ab5fe0e" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'