trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps: 
- task: katalonTask@0
  inputs:
    version: '8.0.1'
    executeArgs: '-browserType="Chrome (headless)" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Regression Suite/TS Cure Health Care" -apiKey="41128eee-c695-4561-b007-a4dc8c81a305" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'